# .github/labeler.yml

area/systems:
  - changed-files:
    - any-glob-to-any-file: 'hosts/**'

area/modules:
  - changed-files:
    - any-glob-to-any-file: 'library/**'

area/documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

area/automation:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

area/packages:
  - changed-files:
    - any-glob-to-any-file: 'packages/**'

area/config:
  - changed-files:
    - any-glob-to-any-file:
      - 'flake.nix'
      - 'flake.lock'
      - '*.toml'
      - '.pre-commit-config.yaml'
      - '.gitignore'
