# https://github.com/getsops/sops
#
# This file defines which keys can encrypt/decrypt secrets.
# When forking this repo, replace the age public key with your own.
#
# Generate your key:
#   age-keygen -o ~/.config/sops/age/keys.txt
#
# Get your public key:
#   age-keygen -y ~/.config/sops/age/keys.txt
#
# Then replace the key below with your public key.

keys:
  - &primary age1nh8nrhlyndr52g904hjpuxzywaeexu6hx2nwztvr8j2fvw9m5czscu92hxs
  # - &desktop age1xxx  # ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *primary

# - path_regex: secrets/desktop/.*\.yaml$
#   key_groups:
#     - age:
#         - *primary
#         - *desktop

# - path_regex: secrets/shared/.*\.yaml$
#   key_groups:
#     - age:
#         - *primary
#         - *desktop
#         - *server
